pipeline {
  agent {
    docker {
      image 'jayshankarkumar/maven-docker-agent:java17'
      args '--user root -v /var/run/docker.sock:/var/run/docker.sock --pull=always'
    }
  }

  environment {
    SONAR_URL = "http://34.227.65.30:9000"
    DOCKER_IMAGE = "jayshankarkumar/springboot-cicd:${BUILD_NUMBER}"
    GIT_REPO_NAME = "CI-CD-Pipeline-Project-new"
    GIT_USER_NAME = "Jayshankarcode"
  }

  stages {

    stage('Checkout') {
      steps {
        git branch: 'main',
            url: 'https://github.com/Jayshankarcode/CI-CD-Pipeline-Project-new.git'
      }
    }

    stage('Build and Test') {
      steps {
        dir('java-maven-sonar-argocd-helm-k8s/spring-boot-app') {
          sh 'mvn clean package'
        }
      }
    }

    stage('Static Code Analysis') {
      steps {
        withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_AUTH_TOKEN')]) {
          dir('java-maven-sonar-argocd-helm-k8s/spring-boot-app') {
            sh """
              mvn sonar:sonar \
              -Dsonar.token=${SONAR_AUTH_TOKEN} \
              -Dsonar.host.url=${SONAR_URL}
            """
          }
        }
      }
    }

    stage('Build and Push Docker Image') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'docker-cred',
          usernameVariable: 'DOCKER_USER',
          passwordVariable: 'DOCKER_PASS'
        )]) {
          script {
            dir('java-maven-sonar-argocd-helm-k8s/spring-boot-app') {
              sh 'docker build -t ${DOCKER_IMAGE} .'
            }

            sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
            sh 'docker push ${DOCKER_IMAGE}'
          }
        }
      }
    }

    stage('Update Deployment File') {
      steps {
        withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
          sh """
            git config user.email "jayshankarkumar@gmail.com"
            git config user.name "Jay Shankar Kumar"

            sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" \
            java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml

            git add java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
            git commit -m "Update deployment image to ${BUILD_NUMBER}" || echo "No changes to commit"
            git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}.git HEAD:main
          """
        }
      }
    }
  }
}
